print("Hello! I am a calculator!")
print("Enter two numbers and I will calculate the result.")
number_1 = int(input("Enter the first number: "))
number_2 = int(input("Enter the second number: "))
print()
print("Addition:       ", number_1 + number_2)
print("Subtraction:    ", number_1 - number_2)
print("Multiplication: ", number_1 * number_2)
print("Division:       ", number_1 / number_2)
print("Floor division: ", number_1 // number_2)
print("Remainder:      ", number_1 % number_2)
print("Power:          ", number_1 ** number_2)